### ISSUE TITLE
[Dev] Update Footer Component according to the theme

### ISSUE THREAD

**Issue by iamarasekera** [Software-Lifecycle-Consultants/slc-open-hms#429]

**Comment by Chmx00** [comment]
[Bug #68 ] has been fixed in this.
(https://github.com/Software-Lifecycle-Consultants/slc-open-hms/issues/68)

- We have changed some fonts and font sizes in the UI according to the theme and to maintain consistency.
- Font family : "Inter" to "Mulish"
- ( Copyright © Travala 2021,Terms & Conditions and Privacy Policy ) - font size : "15px" to "16px"
